### ISSUE TITLE
Implement generic types

### ISSUE THREAD

**Issue by Robbepop** [type-metadata/type-metadata#22]
# Generic Types Encoding

## Current Situation

Right now the type metadata encodes instances of generic types as their own types.
For example `Option<i32>` and `Option<f32>` are their own types respectively.
This was simple to implement and also reflects the monomorphisation rules of Rust upon compilation of generic types.

## Problem

However, when using this mechanic for a very generics-loaded project (such as Substrate) this could cause encoding bloat due to all the "similar" but different types.

## Potential Solution

This encoding bloat for generics-heavy projects could be fixed by introducing yet another indirection which is the introduction of generic types.

With this it would be possible to merge "similar" types into one root of type definition.

The implementation costs, however, are significant:
In order to support just Rust and its generics we would need to reflect Rust's generic design in a way. 

This means, we would need to remodel associated types for example or maybe even traits in order to correctly represent a generic type structure such as this:

```rust
trait In {
    type In;
}
trait Out {
    type Out;
}
trait InOut {
    type InOut: In + Out;
}
struct BoxedInOut<T>
where
    T: InOut,
{
    in: Box<T::In>,
    out: Box<T::Out>,
}
```

Sorry that I didn't come up with a simpler example.
Also note that in the future we might also need to support associated consts and const generics if we actually went down this rabbit hole.

## Summary

- `++` fixes encoding bloat for generics-heavy projects
- `--` makes encoding more depending on Rust language (instead of being language agnostic)
- `--` probably breaks current encodings

**Comment by xlc** [comment]
At this stage I don't think the benefits of solve this issue outweighs the downsides.
I propose to wait until there are some large-ish scale projects using this (large ink projects or when srml metadata are generated with this) and then examine how much spaces can be saved by implement this.

**Comment by Robbepop** [comment]
I think so as well but opened this issue to create awareness of this for future tasks.

**Comment by Robbepop** [comment]
Closed since out of bounds for now and since this feature request has the potential to introduce significant additional complexity to the project.
