### ISSUE TITLE
Move crate to its own organization

### ISSUE THREAD

**Issue by Robbepop** [type-metadata/type-metadata#9]
To make working on `type-metadata` easier for people outside of cennznet we should form an organization for people working on it.

The initial admins of the new organization should ideally be @shaopengw (cennznet) and me (parity).

**Comment by xlc** [comment]
what should be the org name? `type-metadata`?

**Comment by Robbepop** [comment]
> what should be the org name? type-metadata?

Not that important so I would just stick with `type-metadata`.

**Comment by Robbepop** [comment]
Thanks for creating the organization. Could you please also make me admin or similar so that in theory at least one person of every company could react to emergencies.

**Comment by xlc** [comment]
Done

**Comment by Robbepop** [comment]
Thanks!
